#!/bin/bash

set -eu
shopt -s nullglob

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
BUILDERPATH="${DIR}/Var/LGNBuilder"

# git clone https://github.com/1711-Games/LGNBuilder.git ${BUILDERPATH}
git clone git@github.com:1711-Games/LGNBuilder.git ${BUILDERPATH}

${BUILDERPATH}/Scripts/generate \
    --lang=Swift \
    --input ${BUILDERPATH}/IntegrationTests/Schema \
    --output ${DIR}/Sources/IntegrationTests/Codegen

buildResult=$?

if [ $buildResult -ne 0 ]; then
    exit $buildResult
fi

swift run --package-path ${DIR} IntegrationTests --tests-directory ${BUILDERPATH}/IntegrationTests/Tests

exit
