#!/bin/bash

shopt -s nullglob

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
BUILDERPATH="${DIR}/Var/LGNBuilder"

git clone git@github.com:1711-Games/LGNBuilder.git ${BUILDERPATH}

set -eu

${BUILDERPATH}/Scripts/generate \
    --lang=Swift \
    --input ${BUILDERPATH}/IntegrationTests/Schema \
    --output ${DIR}/Sources/IntegrationTests/Codegen

swift run --package-path ${DIR} IntegrationTests --tests-directory ${BUILDERPATH}/IntegrationTests/Tests

exit
