import LGNCore

public extension LGNC {
    struct Translation {}
}

public protocol LGNCTranslator {
    func tr(
        _ input: String,
        _ locale: LGNC.Translation.Locale,
        _ interpolation: [String: Any]...
    ) -> String
}

public extension LGNC.Translation {
    struct DummyTranslator: LGNCTranslator {
        @inlinable public func tr(
            _ input: String,
            _ locale: Locale,
            _ interpolations: [String: Any]...
        ) -> String {
            return input
        }
    }
}

public extension LGNC.Translation {
    enum Locale: String {
        case afZA = "af-ZA"
        case amET = "am-ET"
        case arAE = "ar-AE"
        case arBH = "ar-BH"
        case arDZ = "ar-DZ"
        case arEG = "ar-EG"
        case arIQ = "ar-IQ"
        case arJO = "ar-JO"
        case arKW = "ar-KW"
        case arLB = "ar-LB"
        case arLY = "ar-LY"
        case arMA = "ar-MA"
        case arnCL = "arn-CL"
        case arOM = "ar-OM"
        case arQA = "ar-QA"
        case arSA = "ar-SA"
        case arSY = "ar-SY"
        case arTN = "ar-TN"
        case arYE = "ar-YE"
        case asIN = "as-IN"
        case azCyrlAZ = "az-Cyrl-AZ"
        case azLatnAZ = "az-Latn-AZ"
        case baRU = "ba-RU"
        case beBY = "be-BY"
        case bgBG = "bg-BG"
        case bnBD = "bn-BD"
        case bnIN = "bn-IN"
        case boCN = "bo-CN"
        case brFR = "br-FR"
        case bsCyrlBA = "bs-Cyrl-BA"
        case bsLatnBA = "bs-Latn-BA"
        case caES = "ca-ES"
        case coFR = "co-FR"
        case csCZ = "cs-CZ"
        case cyGB = "cy-GB"
        case daDK = "da-DK"
        case deAT = "de-AT"
        case deCH = "de-CH"
        case deDE = "de-DE"
        case deLI = "de-LI"
        case deLU = "de-LU"
        case dsbDE = "dsb-DE"
        case dvMV = "dv-MV"
        case elGR = "el-GR"
        case en029 = "en-029"
        case enAU = "en-AU"
        case enBZ = "en-BZ"
        case enCA = "en-CA"
        case enGB = "en-GB"
        case enIE = "en-IE"
        case enIN = "en-IN"
        case enJM = "en-JM"
        case enMY = "en-MY"
        case enNZ = "en-NZ"
        case enPH = "en-PH"
        case enSG = "en-SG"
        case enTT = "en-TT"
        case enUS = "en-US"
        case enZA = "en-ZA"
        case enZW = "en-ZW"
        case esAR = "es-AR"
        case esBO = "es-BO"
        case esCL = "es-CL"
        case esCO = "es-CO"
        case esCR = "es-CR"
        case esDO = "es-DO"
        case esEC = "es-EC"
        case esES = "es-ES"
        case esGT = "es-GT"
        case esHN = "es-HN"
        case esMX = "es-MX"
        case esNI = "es-NI"
        case esPA = "es-PA"
        case esPE = "es-PE"
        case esPR = "es-PR"
        case esPY = "es-PY"
        case esSV = "es-SV"
        case esUS = "es-US"
        case esUY = "es-UY"
        case esVE = "es-VE"
        case etEE = "et-EE"
        case euES = "eu-ES"
        case faIR = "fa-IR"
        case fiFI = "fi-FI"
        case filPH = "fil-PH"
        case foFO = "fo-FO"
        case frBE = "fr-BE"
        case frCA = "fr-CA"
        case frCH = "fr-CH"
        case frFR = "fr-FR"
        case frLU = "fr-LU"
        case frMC = "fr-MC"
        case fyNL = "fy-NL"
        case gaIE = "ga-IE"
        case gdGB = "gd-GB"
        case glES = "gl-ES"
        case gswFR = "gsw-FR"
        case guIN = "gu-IN"
        case haLatnNG = "ha-Latn-NG"
        case heIL = "he-IL"
        case hiIN = "hi-IN"
        case hrBA = "hr-BA"
        case hrHR = "hr-HR"
        case hsbDE = "hsb-DE"
        case huHU = "hu-HU"
        case hyAM = "hy-AM"
        case idID = "id-ID"
        case igNG = "ig-NG"
        case iiCN = "ii-CN"
        case isIS = "is-IS"
        case itCH = "it-CH"
        case itIT = "it-IT"
        case iuCansCA = "iu-Cans-CA"
        case iuLatnCA = "iu-Latn-CA"
        case jaJP = "ja-JP"
        case kaGE = "ka-GE"
        case kkKZ = "kk-KZ"
        case klGL = "kl-GL"
        case kmKH = "km-KH"
        case knIN = "kn-IN"
        case kokIN = "kok-IN"
        case koKR = "ko-KR"
        case kyKG = "ky-KG"
        case lbLU = "lb-LU"
        case loLA = "lo-LA"
        case ltLT = "lt-LT"
        case lvLV = "lv-LV"
        case miNZ = "mi-NZ"
        case mkMK = "mk-MK"
        case mlIN = "ml-IN"
        case mnMN = "mn-MN"
        case mnMongCN = "mn-Mong-CN"
        case mohCA = "moh-CA"
        case mrIN = "mr-IN"
        case msBN = "ms-BN"
        case msMY = "ms-MY"
        case mtMT = "mt-MT"
        case nbNO = "nb-NO"
        case neNP = "ne-NP"
        case nlBE = "nl-BE"
        case nlNL = "nl-NL"
        case nnNO = "nn-NO"
        case nsoZA = "nso-ZA"
        case ocFR = "oc-FR"
        case orIN = "or-IN"
        case paIN = "pa-IN"
        case plPL = "pl-PL"
        case prsAF = "prs-AF"
        case psAF = "ps-AF"
        case ptBR = "pt-BR"
        case ptPT = "pt-PT"
        case qutGT = "qut-GT"
        case quzBO = "quz-BO"
        case quzEC = "quz-EC"
        case quzPE = "quz-PE"
        case rmCH = "rm-CH"
        case roRO = "ro-RO"
        case ruRU = "ru-RU"
        case rwRW = "rw-RW"
        case sahRU = "sah-RU"
        case saIN = "sa-IN"
        case seFI = "se-FI"
        case seNO = "se-NO"
        case seSE = "se-SE"
        case siLK = "si-LK"
        case skSK = "sk-SK"
        case slSI = "sl-SI"
        case smaNO = "sma-NO"
        case smaSE = "sma-SE"
        case smjNO = "smj-NO"
        case smjSE = "smj-SE"
        case smnFI = "smn-FI"
        case smsFI = "sms-FI"
        case sqAL = "sq-AL"
        case srCyrlBA = "sr-Cyrl-BA"
        case srCyrlCS = "sr-Cyrl-CS"
        case srCyrlME = "sr-Cyrl-ME"
        case srCyrlRS = "sr-Cyrl-RS"
        case srLatnBA = "sr-Latn-BA"
        case srLatnCS = "sr-Latn-CS"
        case srLatnME = "sr-Latn-ME"
        case srLatnRS = "sr-Latn-RS"
        case svFI = "sv-FI"
        case svSE = "sv-SE"
        case swKE = "sw-KE"
        case syrSY = "syr-SY"
        case taIN = "ta-IN"
        case teIN = "te-IN"
        case tgCyrlTJ = "tg-Cyrl-TJ"
        case thTH = "th-TH"
        case tkTM = "tk-TM"
        case tnZA = "tn-ZA"
        case trTR = "tr-TR"
        case ttRU = "tt-RU"
        case tzmLatnDZ = "tzm-Latn-DZ"
        case ugCN = "ug-CN"
        case ukUA = "uk-UA"
        case urPK = "ur-PK"
        case uzCyrlUZ = "uz-Cyrl-UZ"
        case uzLatnUZ = "uz-Latn-UZ"
        case viVN = "vi-VN"
        case woSN = "wo-SN"
        case xhZA = "xh-ZA"
        case yoNG = "yo-NG"
        case zhCN = "zh-CN"
        case zhHK = "zh-HK"
        case zhMO = "zh-MO"
        case zhSG = "zh-SG"
        case zhTW = "zh-TW"
        case zuZA = "zu-ZA"

        public init(_ locale: String) {
            if let instance = Locale(rawValue: locale) {
                self = instance
                return
            }

            let instance: Locale = .enUS
            LGNCore.log("Invalid locale: \(locale), falling back to \(instance)")
            self = instance
        }
    }
}
